import { NextResponse } from 'next/server'

export async function GET() {

	const options = ["completed", "in_progress", "queued"]
	const result = options[Math.floor(Math.random() * options.length)]

	return NextResponse.json({
		"total_count": 287,
		"workflow_runs": [
			// status (in_progress | completed | queued)
			// name
			// conclusion
			{
				"id": 16499242612,
				"name": "pages build and deployment", // <---
				"node_id": "WFR_kwLOOakdl88AAAAD1252dA",
				"head_branch": "gh-pages",
				"head_sha": "b8188e95e4781bcaf31dd3a78bfddb751d19da37",
				"path": "dynamic/pages/pages-build-deployment",
				"display_title": "pages build and deployment",
				"run_number": 128,
				"event": "dynamic",
				"status": result, // <--- in_progress | completed | queued
				"conclusion": "success", // <----
				"workflow_id": 156501291,
				"check_suite_id": 42292662909,
				"check_suite_node_id": "CS_kwDOOakdl88AAAAJ2NbSfQ",
				"url": "https://api.github.com/repos/bnz/area-next/actions/runs/16499242612",
				"html_url": "https://github.com/bnz/area-next/actions/runs/16499242612",
				"pull_requests": [],
				"created_at": "2025-07-24T14:10:01Z",
				"updated_at": "2025-07-24T14:10:25Z",
				"actor": {
					"login": "github-pages[bot]",
					"id": 52472962,
					"node_id": "MDM6Qm90NTI0NzI5NjI=",
					"avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/github-pages%5Bbot%5D",
					"html_url": "https://github.com/apps/github-pages",
					"followers_url": "https://api.github.com/users/github-pages%5Bbot%5D/followers",
					"following_url": "https://api.github.com/users/github-pages%5Bbot%5D/following{/other_user}",
					"gists_url": "https://api.github.com/users/github-pages%5Bbot%5D/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/github-pages%5Bbot%5D/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/github-pages%5Bbot%5D/subscriptions",
					"organizations_url": "https://api.github.com/users/github-pages%5Bbot%5D/orgs",
					"repos_url": "https://api.github.com/users/github-pages%5Bbot%5D/repos",
					"events_url": "https://api.github.com/users/github-pages%5Bbot%5D/events{/privacy}",
					"received_events_url": "https://api.github.com/users/github-pages%5Bbot%5D/received_events",
					"type": "Bot",
					"user_view_type": "public",
					"site_admin": false,
				},
				"run_attempt": 1,
				"referenced_workflows": [],
				"run_started_at": "2025-07-24T14:10:01Z",
				"triggering_actor": {
					"login": "github-pages[bot]",
					"id": 52472962,
					"node_id": "MDM6Qm90NTI0NzI5NjI=",
					"avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/github-pages%5Bbot%5D",
					"html_url": "https://github.com/apps/github-pages",
					"followers_url": "https://api.github.com/users/github-pages%5Bbot%5D/followers",
					"following_url": "https://api.github.com/users/github-pages%5Bbot%5D/following{/other_user}",
					"gists_url": "https://api.github.com/users/github-pages%5Bbot%5D/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/github-pages%5Bbot%5D/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/github-pages%5Bbot%5D/subscriptions",
					"organizations_url": "https://api.github.com/users/github-pages%5Bbot%5D/orgs",
					"repos_url": "https://api.github.com/users/github-pages%5Bbot%5D/repos",
					"events_url": "https://api.github.com/users/github-pages%5Bbot%5D/events{/privacy}",
					"received_events_url": "https://api.github.com/users/github-pages%5Bbot%5D/received_events",
					"type": "Bot",
					"user_view_type": "public",
					"site_admin": false,
				},
				"jobs_url": "https://api.github.com/repos/bnz/area-next/actions/runs/16499242612/jobs",
				"logs_url": "https://api.github.com/repos/bnz/area-next/actions/runs/16499242612/logs",
				"check_suite_url": "https://api.github.com/repos/bnz/area-next/check-suites/42292662909",
				"artifacts_url": "https://api.github.com/repos/bnz/area-next/actions/runs/16499242612/artifacts",
				"cancel_url": "https://api.github.com/repos/bnz/area-next/actions/runs/16499242612/cancel",
				"rerun_url": "https://api.github.com/repos/bnz/area-next/actions/runs/16499242612/rerun",
				"previous_attempt_url": null,
				"workflow_url": "https://api.github.com/repos/bnz/area-next/actions/workflows/156501291",
				"head_commit": {
					"id": "b8188e95e4781bcaf31dd3a78bfddb751d19da37",
					"tree_id": "6d13ba0f77b9892209c48674727efbe5dc798940",
					"message": "deploy: 763af615c0ac8098caf61ec19c84848486b3943e",
					"timestamp": "2025-07-24T14:09:59Z",
					"author": {
						"name": "bnz",
						"email": "bnz@users.noreply.github.com",
					},
					"committer": {
						"name": "bnz",
						"email": "bnz@users.noreply.github.com",
					},
				},
				"repository": {
					"id": 967384471,
					"node_id": "R_kgDOOakdlw",
					"name": "area-next",
					"full_name": "bnz/area-next",
					"private": false,
					"owner": {
						"login": "bnz",
						"id": 1963658,
						"node_id": "MDQ6VXNlcjE5NjM2NTg=",
						"avatar_url": "https://avatars.githubusercontent.com/u/1963658?v=4",
						"gravatar_id": "",
						"url": "https://api.github.com/users/bnz",
						"html_url": "https://github.com/bnz",
						"followers_url": "https://api.github.com/users/bnz/followers",
						"following_url": "https://api.github.com/users/bnz/following{/other_user}",
						"gists_url": "https://api.github.com/users/bnz/gists{/gist_id}",
						"starred_url": "https://api.github.com/users/bnz/starred{/owner}{/repo}",
						"subscriptions_url": "https://api.github.com/users/bnz/subscriptions",
						"organizations_url": "https://api.github.com/users/bnz/orgs",
						"repos_url": "https://api.github.com/users/bnz/repos",
						"events_url": "https://api.github.com/users/bnz/events{/privacy}",
						"received_events_url": "https://api.github.com/users/bnz/received_events",
						"type": "User",
						"user_view_type": "public",
						"site_admin": false,
					},
					"html_url": "https://github.com/bnz/area-next",
					"description": null,
					"fork": false,
					"url": "https://api.github.com/repos/bnz/area-next",
					"forks_url": "https://api.github.com/repos/bnz/area-next/forks",
					"keys_url": "https://api.github.com/repos/bnz/area-next/keys{/key_id}",
					"collaborators_url": "https://api.github.com/repos/bnz/area-next/collaborators{/collaborator}",
					"teams_url": "https://api.github.com/repos/bnz/area-next/teams",
					"hooks_url": "https://api.github.com/repos/bnz/area-next/hooks",
					"issue_events_url": "https://api.github.com/repos/bnz/area-next/issues/events{/number}",
					"events_url": "https://api.github.com/repos/bnz/area-next/events",
					"assignees_url": "https://api.github.com/repos/bnz/area-next/assignees{/user}",
					"branches_url": "https://api.github.com/repos/bnz/area-next/branches{/branch}",
					"tags_url": "https://api.github.com/repos/bnz/area-next/tags",
					"blobs_url": "https://api.github.com/repos/bnz/area-next/git/blobs{/sha}",
					"git_tags_url": "https://api.github.com/repos/bnz/area-next/git/tags{/sha}",
					"git_refs_url": "https://api.github.com/repos/bnz/area-next/git/refs{/sha}",
					"trees_url": "https://api.github.com/repos/bnz/area-next/git/trees{/sha}",
					"statuses_url": "https://api.github.com/repos/bnz/area-next/statuses/{sha}",
					"languages_url": "https://api.github.com/repos/bnz/area-next/languages",
					"stargazers_url": "https://api.github.com/repos/bnz/area-next/stargazers",
					"contributors_url": "https://api.github.com/repos/bnz/area-next/contributors",
					"subscribers_url": "https://api.github.com/repos/bnz/area-next/subscribers",
					"subscription_url": "https://api.github.com/repos/bnz/area-next/subscription",
					"commits_url": "https://api.github.com/repos/bnz/area-next/commits{/sha}",
					"git_commits_url": "https://api.github.com/repos/bnz/area-next/git/commits{/sha}",
					"comments_url": "https://api.github.com/repos/bnz/area-next/comments{/number}",
					"issue_comment_url": "https://api.github.com/repos/bnz/area-next/issues/comments{/number}",
					"contents_url": "https://api.github.com/repos/bnz/area-next/contents/{+path}",
					"compare_url": "https://api.github.com/repos/bnz/area-next/compare/{base}...{head}",
					"merges_url": "https://api.github.com/repos/bnz/area-next/merges",
					"archive_url": "https://api.github.com/repos/bnz/area-next/{archive_format}{/ref}",
					"downloads_url": "https://api.github.com/repos/bnz/area-next/downloads",
					"issues_url": "https://api.github.com/repos/bnz/area-next/issues{/number}",
					"pulls_url": "https://api.github.com/repos/bnz/area-next/pulls{/number}",
					"milestones_url": "https://api.github.com/repos/bnz/area-next/milestones{/number}",
					"notifications_url": "https://api.github.com/repos/bnz/area-next/notifications{?since,all,participating}",
					"labels_url": "https://api.github.com/repos/bnz/area-next/labels{/name}",
					"releases_url": "https://api.github.com/repos/bnz/area-next/releases{/id}",
					"deployments_url": "https://api.github.com/repos/bnz/area-next/deployments",
				},
				"head_repository": {
					"id": 967384471,
					"node_id": "R_kgDOOakdlw",
					"name": "area-next",
					"full_name": "bnz/area-next",
					"private": false,
					"owner": {
						"login": "bnz",
						"id": 1963658,
						"node_id": "MDQ6VXNlcjE5NjM2NTg=",
						"avatar_url": "https://avatars.githubusercontent.com/u/1963658?v=4",
						"gravatar_id": "",
						"url": "https://api.github.com/users/bnz",
						"html_url": "https://github.com/bnz",
						"followers_url": "https://api.github.com/users/bnz/followers",
						"following_url": "https://api.github.com/users/bnz/following{/other_user}",
						"gists_url": "https://api.github.com/users/bnz/gists{/gist_id}",
						"starred_url": "https://api.github.com/users/bnz/starred{/owner}{/repo}",
						"subscriptions_url": "https://api.github.com/users/bnz/subscriptions",
						"organizations_url": "https://api.github.com/users/bnz/orgs",
						"repos_url": "https://api.github.com/users/bnz/repos",
						"events_url": "https://api.github.com/users/bnz/events{/privacy}",
						"received_events_url": "https://api.github.com/users/bnz/received_events",
						"type": "User",
						"user_view_type": "public",
						"site_admin": false,
					},
					"html_url": "https://github.com/bnz/area-next",
					"description": null,
					"fork": false,
					"url": "https://api.github.com/repos/bnz/area-next",
					"forks_url": "https://api.github.com/repos/bnz/area-next/forks",
					"keys_url": "https://api.github.com/repos/bnz/area-next/keys{/key_id}",
					"collaborators_url": "https://api.github.com/repos/bnz/area-next/collaborators{/collaborator}",
					"teams_url": "https://api.github.com/repos/bnz/area-next/teams",
					"hooks_url": "https://api.github.com/repos/bnz/area-next/hooks",
					"issue_events_url": "https://api.github.com/repos/bnz/area-next/issues/events{/number}",
					"events_url": "https://api.github.com/repos/bnz/area-next/events",
					"assignees_url": "https://api.github.com/repos/bnz/area-next/assignees{/user}",
					"branches_url": "https://api.github.com/repos/bnz/area-next/branches{/branch}",
					"tags_url": "https://api.github.com/repos/bnz/area-next/tags",
					"blobs_url": "https://api.github.com/repos/bnz/area-next/git/blobs{/sha}",
					"git_tags_url": "https://api.github.com/repos/bnz/area-next/git/tags{/sha}",
					"git_refs_url": "https://api.github.com/repos/bnz/area-next/git/refs{/sha}",
					"trees_url": "https://api.github.com/repos/bnz/area-next/git/trees{/sha}",
					"statuses_url": "https://api.github.com/repos/bnz/area-next/statuses/{sha}",
					"languages_url": "https://api.github.com/repos/bnz/area-next/languages",
					"stargazers_url": "https://api.github.com/repos/bnz/area-next/stargazers",
					"contributors_url": "https://api.github.com/repos/bnz/area-next/contributors",
					"subscribers_url": "https://api.github.com/repos/bnz/area-next/subscribers",
					"subscription_url": "https://api.github.com/repos/bnz/area-next/subscription",
					"commits_url": "https://api.github.com/repos/bnz/area-next/commits{/sha}",
					"git_commits_url": "https://api.github.com/repos/bnz/area-next/git/commits{/sha}",
					"comments_url": "https://api.github.com/repos/bnz/area-next/comments{/number}",
					"issue_comment_url": "https://api.github.com/repos/bnz/area-next/issues/comments{/number}",
					"contents_url": "https://api.github.com/repos/bnz/area-next/contents/{+path}",
					"compare_url": "https://api.github.com/repos/bnz/area-next/compare/{base}...{head}",
					"merges_url": "https://api.github.com/repos/bnz/area-next/merges",
					"archive_url": "https://api.github.com/repos/bnz/area-next/{archive_format}{/ref}",
					"downloads_url": "https://api.github.com/repos/bnz/area-next/downloads",
					"issues_url": "https://api.github.com/repos/bnz/area-next/issues{/number}",
					"pulls_url": "https://api.github.com/repos/bnz/area-next/pulls{/number}",
					"milestones_url": "https://api.github.com/repos/bnz/area-next/milestones{/number}",
					"notifications_url": "https://api.github.com/repos/bnz/area-next/notifications{?since,all,participating}",
					"labels_url": "https://api.github.com/repos/bnz/area-next/labels{/name}",
					"releases_url": "https://api.github.com/repos/bnz/area-next/releases{/id}",
					"deployments_url": "https://api.github.com/repos/bnz/area-next/deployments",
				},
			},
		],
	})
}

export async function POST(request: Request) {
	const body = await request.json()
	return NextResponse.json({ received: body })
}
